### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Arthurdw** [datasciencedojo/tutorials#1]
Hey.
For some reason, your youtube tutorial called "Intro to Web Scraping with Python and Beautiful Soup" doesn't work for me.
So, I thought maybe it's because of me, maybe I'm doing something wrong.
So to test this I copied your code into a file and ran it.
The error that I received was this:
```
Traceback (most recent call last):
  File "My Directory", line 36, in <module>
    brand = make_rating_sp[0].img["title"].title()
TypeError: 'NoneType' object is not subscriptable
```
The code that I inserted was this:
```python
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq

page_url = "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&N=-1&IsNodeId=1&Description=GTX&bop=And&Page=1&PageSize=36&order=BESTMATCH"
uClient = uReq(page_url)
page_soup = soup(uClient.read(), "html.parser")
uClient.close()
containers = page_soup.findAll("div", {"class": "item-container"})
out_filename = "graphics_cards.csv"
headers = "brand,product_name,shipping \n"
f = open(out_filename, "w")
f.write(headers)

for container in containers:
    make_rating_sp = container.div.select("a")
    brand = make_rating_sp[0].img["title"].title()
    product_name = container.div.select("a")[2].text
    shipping = container.findAll("li", {"class": "price-ship"})[0].text.strip().replace("$", "").replace(" Shipping", "")
    print("brand: " + brand + "\n")
    print("product_name: " + product_name + "\n")
    print("shipping: " + shipping + "\n")
    f.write(brand + ", " + product_name.replace(",", "|") + ", " + shipping + "\n")

f.close()
```

I do know why that error occurs but if its stated in the video maybe other things aren't valid to this day neither.
Greetings Arthur.

**Comment by Arthurdw** [comment]
Site changed and code **wasn't valid** for the site anymore.

**Comment by oumarsow94** [comment]
Hi I have the same problems can you help me

**Comment by Arthurdw** [comment]
> Hi I have the same problems can you help me

The error states that it has nothing to extract. 
So check if your object has a value.   
```python
print(type(make_rating_sp)) 
```
  
If not take a look at the HTML code, and update your Python code.  
If its does send your code here please. ^^

Good luck.   
- Arthurdw

**Comment by Harikrishna30** [comment]
print(type(make_rating_sp))
it's list

**Comment by Harikrishna30** [comment]
please share how to retified the error

**Comment by Arthurdw** [comment]
Update your python code according to the HTML code from your website.
_(as said before)_

Could you please share some more details @Harikrishna30 ?
Thanks!
